#!/bin/bash 

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NOCOLOR='\033[0m'

APPFAIL=0
LEAVECUZILOVEFIGLET=0
NOFIGLET=0

clear
echo -e "${YELLOW}↻ Checking for dependencies...↻${NOCOLOR}"

if [ ! -f /usr/bin/git ]
then
    echo -e "${GREEN}⬇ Installing git...⬇${NOCOLOR}"
    sudo apt install git
    if [ ! -f /usr/bin/git ]
    then
    echo -e "${RED}Installation Failed! Check your connection"
    echo -e "${RED}and try again.${NOCOLOR}"
    read -n 1 -s -r -p "Press any key to continue..."
    exit
    fi
elif [ ! -f /usr/bin/curl ]
then
    echo -e "${GREEN}⬇ Installing curl...⬇${NOCOLOR}"
    sudo apt install curl
    if [ ! -f /usr/bin/curl ]
    then
    echo -e "${RED}Installation Failed! Check your connection"
    echo -e "${RED}and try again.${NOCOLOR}"
    read -n 1 -s -r -p "Press any key to continue..."
    exit
    fi
elif [ ! -f /usr/bin/figlet ]
then
    echo -e "${GREEN}⬇ Installing figlet...⬇${NOCOLOR}"
    sudo apt install figlet
    if [ ! -f /usr/bin/figlet ]
    then
    echo -e "${YELLOW}Failed installing figlet, an optional"
    echo -e "${YELLOW}dependency. Would you like to continue?${NOCOLOR} [y/n]"
    NOFIGLET=1
    read CONTINUEWITHOUTFIGLET
    if [ ! $CONTINUEWITHOUTFIGLET == y ]
    then
        LEAVECUZILOVEFIGLET=1
    elif [ $CONTINUEWITHOUTFIGLET == Y ]
    then
        LEAVECUZILOVEFIGLET=0
        fi
    fi
fi

if [ $LEAVECUZILOVEFIGLET == 1 ]
then
    exit
fi

#Selection Menu

while true; do

clear

printf ${RED}
if [ ! $NOFIGLET == 1 ]
then
    figlet "Piper"
fi

echo "Piper Terminal Deck"
printf ${NOCOLOR}

echo ""
echo "Select an option:"
echo "1: Exit (Close Piper)"
echo "2: Pi-Apps (Appstore For Pi)"
echo "3: piKiss (Download Tools For Pi)"
echo "4: Edit Configuration (Edit config.txt)"
echo "5: Neofetch (Get System Info)"
echo "6: HTop (Terminal Task Manager)"
read MENU

case $MENU in
  2)
    clear
    if [ ! $NOFIGLET == 1 ]
    then
        figlet "Pi-Apps"
    fi
    if [ ! -d /home/$USER/pi-apps ]
    then
        cd /home/$USER
        echo -e "${GREEN}⬇ Installing Pi-Apps...⬇${NOCOLOR}"
        wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
        if [ ! -f /home/$USER/pi-apps/gui ]
        then
            echo -e "${RED}Installation Failed! Check your connection"
            echo -e "${RED}and try again.${NOCOLOR}"
            APPFAIL=1
        fi
    fi
    if [ $APPFAIL == 0 ]
    then
        /home/$USER/pi-apps/gui
    fi
    ;;
    
  3)
    clear
    if [ ! $NOFIGLET == 1 ]
    then
        figlet "piKiss"
    fi
    echo -e "${YELLOW}WARNING:"
    echo -e "${YELLOW}Sometimes, you may need to run piKiss twice.${NOCOLOR}"
    if [ ! -d /home/$USER/piKiss ]
    then
        echo -e "${GREEN}⬇ Installing piKiss...⬇${NOCOLOR}"
        cd /home/$USER
        curl -sSL https://git.io/JfAPE | bash
        if [ ! -f /home/$USER/piKiss/piKiss.sh ]
        then
            echo -e "${RED}Installation Failed! Check your connection"
            echo -e "${RED}and try again.${NOCOLOR}"
            APPFAIL=1
        fi
    fi
    if [ $APPFAIL == 0 ]
    then
        /home/$USER/piKiss/piKiss.sh
    fi
    ;;

  4)
    clear
    if [ ! $NOFIGLET == 1 ]
    then
        figlet "nano"
    fi
    if [ ! -f /usr/bin/nano ]
    then
        echo -e "${GREEN}⬇ Installing nano...⬇${NOCOLOR}"
        sudo apt-get install nano
        if [ ! -f /usr/bin/nano ]
        then
            echo -e "${RED}Installation Failed! Check your connection"
            echo -e "${RED}and try again.${NOCOLOR}"
            APPFAIL=1
        fi
    fi
    if [ $APPFAIL == 0 ]
    then
        sudo nano '/boot/firmware/config.txt'
    fi
    ;;
    
  1)
    clear
        case $((1 + $RANDOM % 10)) in
        1)
            TEXT="It's getting late. ${BLUE}You shouldn't go out alone.${NOCOLOR}"
            ;;

        2)
            TEXT="C'mon! Just ${YELLOW}one more game!${NOCOLOR}"
            ;;

        3)
            TEXT="${RED}WAIT! DON'T GO!!!${NOCOLOR}"
            ;;
            
        4)
            TEXT="But there's still plenty of goodies!"
            ;;
            
        5)
            TEXT="If you leave, ${RED}you are dead to me.${NOCOLOR}"
            ;;
            
        6)
            TEXT="The user ${GREEN}$USER${NOCOLOR} is confronted with a difficult decision:"
            ;;
            
        7)
            TEXT="Hol' up,"
            ;;
            
        8)
            TEXT="Wait, but don't you ${RED}love${NOCOLOR} me?"
            ;;
            
        9)
            TEXT="Your ${RED}Raspberry Pi${NOCOLOR} is counting on you!"
            ;;
            
        10)
            TEXT=":${BLUE}'${NOCOLOR}("
            ;;
            
        esac
    if [ ! $NOFIGLET == 1 ]
    then
        figlet "Quit?"
    fi
    echo -e $TEXT
    read -p "Are you sure you want to quit? [y/n]" EXIT
    if [ $EXIT == "y" ]
    then
        clear
        echo -e "From yours truly, ${RED}PizzaPocketHut${NOCOLOR}."
        exit
    elif [ $EXIT == "Y" ]
    then
        clear
        exit
    fi
    ;;
    
    5)
    clear
    if [ ! $NOFIGLET == 1 ]
    then
        figlet "Neofetch"
    fi
    if [ ! -f /usr/bin/neofetch ]
    then
        echo -e "${GREEN}⬇ Installing Neofetch...⬇${NOCOLOR}"
        sudo apt-get install neofetch
        if [ ! -f /usr/bin/neofetch ]
        then
            echo -e "${RED}Installation Failed! Check your connection"
            echo -e "${RED}and try again.${NOCOLOR}"
            APPFAIL=1
        fi
    fi
    if [ $APPFAIL == 0 ]
    then
        neofetch
        read -n 1 -s -r -p "Press any key to continue..."
    fi
    ;;
    
    6)
    clear
    if [ ! $NOFIGLET == 1 ]
    then
        figlet "HTop"
    fi
    if [ ! -f /usr/bin/htop ]
    then
        echo -e "${GREEN}⬇ Installing HTop...⬇${NOCOLOR}"
        sudo apt-get install htop
        if [ ! -f /usr/bin/htop ]
        then
            echo -e "${RED}Installation Failed! Check your connection"
            echo -e "${RED}and try again.${NOCOLOR}"
            APPFAIL=1
        fi
    fi
    if [ $APPFAIL == 0 ]
    then
        htop
    fi    
    ;;
esac

done

